server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
spring:
  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v{version:\d+}/deliveries/**, /api/v{version:\d+}/couriers/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v{version:\d+}/orders/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/v{version:\d+}/auth/** #, /api/v{version:\d+}/users/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: "*"