name: Update sdfProBEVersion on PR Merge

on:
  push:
    branches:
      - qa
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update SdfProBEVersion
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            current_version=$(grep 'sdfProBEVersion=' gradle.properties | cut -d'=' -f2)

            IFS='.' read -ra version_parts <<< "$current_version"
            major="${version_parts[0]}"
            minor="${version_parts[1]}"
            patch="${version_parts[2]}"
            build="${version_parts[3]}"

            ((build++))

            build=$(printf "%04d" $build)

            new_version="$major.$minor.$patch.$build"
            sed -i "s/sdfProBEVersion=$current_version/sdfProBEVersion=$new_version/" gradle.properties

            git config user.name "${{ github.event.pull_request.user.login }}"
            git config user.email "${{ github.event.pull_request.user.email }}"
          
            git add gradle.properties
            git commit -m "Update SdfProBEVersion to $new_version"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
